name = "PMParameterizedSensitivity"
uuid = "a582606a-6a0f-441d-bade-777196214a17"
authors = ["Timothy Knab"]
version = "1.0.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
PMParameterizedBase = "99b5832f-53bf-45ba-a9c8-837ddefabddf"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"

[compat]
julia = "1.9.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
