name = "PMParameterizedSensitivity"
uuid = "a582606a-6a0f-441d-bade-777196214a17"
authors = ["Timothy Knab"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
